<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v2jjSv5' shared service.

return $this->privates['.service_locator.v2jjSv5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::new' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PartenaireController:new' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\PartenaireController::new' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\PartenaireController:new' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
