<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d6B9ACh' shared service.

return $this->privates['.service_locator.d6B9ACh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ListeController::index' => ['privates', '.service_locator.OIueEnh', 'get_ServiceLocator_OIueEnhService.php', true],
    'App\\Controller\\PartenaireController::ajoutP' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\SecurityController::index' => ['privates', '.service_locator.OIueEnh', 'get_ServiceLocator_OIueEnhService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController::update' => ['privates', '.service_locator.sFS5.mG', 'get_ServiceLocator_SFS5_MGService.php', true],
    'App\\Controller\\ListeController:index' => ['privates', '.service_locator.OIueEnh', 'get_ServiceLocator_OIueEnhService.php', true],
    'App\\Controller\\PartenaireController:ajoutP' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\SecurityController:index' => ['privates', '.service_locator.OIueEnh', 'get_ServiceLocator_OIueEnhService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController:update' => ['privates', '.service_locator.sFS5.mG', 'get_ServiceLocator_SFS5_MGService.php', true],
], [
    'App\\Controller\\ListeController::index' => '?',
    'App\\Controller\\PartenaireController::ajoutP' => '?',
    'App\\Controller\\PartenaireController::depot' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\SecurityController::index' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\SecurityController::update' => '?',
    'App\\Controller\\ListeController:index' => '?',
    'App\\Controller\\PartenaireController:ajoutP' => '?',
    'App\\Controller\\PartenaireController:depot' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\SecurityController:index' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\SecurityController:update' => '?',
]);
