<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLMsobYV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLMsobYV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLMsobYV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLMsobYV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLMsobYV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LMsobYV',
    'container.build_id' => 'c8073965',
    'container.build_time' => 1564157548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLMsobYV');
