<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZq1xoSS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZq1xoSS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZq1xoSS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZq1xoSS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZq1xoSS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Zq1xoSS',
    'container.build_id' => '2df442fe',
    'container.build_time' => 1564142398,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZq1xoSS');
