<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZMmjxHZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMmjxHZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMmjxHZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZMmjxHZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZMmjxHZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZMmjxHZ',
    'container.build_id' => 'f58df05a',
    'container.build_time' => 1564478421,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMmjxHZ');
